feat: add dockerfile, service.yml and deployment.yml files to auth se…
frmscoe/auth-service pull request #19
Opened 2024-07-30 05:54 UTC by scott45

# SPDX-License-Identifier: Apache-2.0

## What did we change?
Add a dockerfile, service.yml and deployment.yml to auth-service.

## Why are we doing this?
They are required as deployable files

## How was it tested?
- [x] Locally
- [x] Development Environment
- [ ] Not needed, changes very basic
- [ ] Husky successfully run
- [ ] Unit tests passing and Documentation done

![Screenshot 2024-08-01 at 11 06 23 (2)](https://github.com/user-attachments/assets/4740c4db-4115-4ad4-8ca3-1e40fb761e2b)

2024-07-30 07:22 UTC, cshezi commented
Let's answer PR questioners

2024-07-30 07:36 UTC, cshezi requested changes

2024-07-30 07:36 UTC, cshezi commented on Dockerfile
> +ENV DATABASE_URL=
Environment variables are not being used in this service e.g REDIS

2024-07-30 07:36 UTC, cshezi commented on Dockerfile
> +EXPOSE 4222
Consider exposing the rest port this port is used for NATS subscription

2024-07-31 07:21 UTC, cshezi requested changes
We are missing a couple of Environment variables

![image](https://github.com/user-attachments/assets/32831e10-e2a8-495e-a57f-864c5bcc92f0)

2024-07-31 07:23 UTC, cshezi commented
Please try starting up the image and try GET`/health` endpoint to see if the service is up and running

2024-08-01 11:43 UTC, cshezi approved these changes
LGTM

2024-08-11 19:37 UTC, Justus-at-Tazama approved these changes

2024-08-11 19:37 UTC, merged